name: Twitter Bot

on:
  schedule:
    # Run at random times throughout the day
    - cron: '0 8-23/4 * * *'  # Every 4 hours between 8 AM and 11 PM
    - cron: '30 9-22/3 * * *'  # Every 3 hours between 9:30 AM and 10:30 PM
    - cron: '15 10-21/2 * * *'  # Every 2 hours between 10:15 AM and 9:15 PM
  # Allows manual triggering from GitHub Actions tab
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Twitter Bot
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TWITTER_API_KEY: ${{ secrets.API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.API_KEY_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        BOT_TOPICS: ${{ secrets.BOT_TOPICS }}
        BOT_PERSONALITY: ${{ secrets.BOT_PERSONALITY }}
        TWEETS_PER_TOPIC: ${{ secrets.TWEETS_PER_TOPIC }}
      run: python main.py 